core:
  corecruncher: false
  corecruncher_script: /path/to/corecruncher_master.py
  enabled: false
  roary: false
cpus: 4
deg:
  deg_coverage_filter: 0
  deg_identity_filter: 0
  enabled: true
metabolism:
  chokepoint_file: /path/to/chokepoints.txt
  enabled: false
  sbml_file: /path/to/model.sbml
  smarttable_file: /path/to/genes_smarttable.tsv
metadata:
  enabled: false
  meta_tables:
  - /path/to/meta_table1.tsv
  - /path/to/meta_table2.tsv
offtarget:
  enabled: true
  human: true
  microbiome: true
  microbiome_coverage_filter: 0
  microbiome_identity_filter: 0
organism:
  gbk_file: /app/targetpathogenweb/data/023/NZ_AP023069.1/NZ_AP023069.1.gbk
  name: Neisseria
  tax_id: 485
psortb:
  enabled: false
  gram_type: n
structures:
  enabled: false
  proteome_uniprot: proteome_uniprot
